config:
    controls:
      swipeThumbSize: 30
      minSwipeDist: 50
      directionSnaps: 4

    #   ██████ ██████  ███████ ██████  ██ ████████ ███████ 
    #  ██      ██   ██ ██      ██   ██ ██    ██    ██      
    #  ██      ██████  █████   ██   ██ ██    ██    ███████ 
    #  ██      ██   ██ ██      ██   ██ ██    ██         ██ 
    #   ██████ ██   ██ ███████ ██████  ██    ██    ███████ 
    #                                                      
    credits:
      - title: Game Design, Programming
        names:
          - Dickson Chui (@vicksonzero)
      - title: Graphics
        names:
          - Dickson Chui
      - title: Free Graphics
          - Kenney (CC0, kenney.nl)
      - title: Free Icons
          - Kenney (CC0, kenney.nl)
          - Quoting (CC BY 3.0, game-icons.net)
          - Rémy Médard (Public Domain, thenounproject.com/catalarem)
      - title: Music / Sound
        names:
          - none yet
      - title: Free Music / Sound
        names:
          - none yet
      - title: Items Design Ideas
        names:
          - Amethyst
          - choiwaikit0613
          - icebee
  
  
  
  
  
  
  
  
  